const { pool }=require('../config/database');
const model=require('../models/userReport.model');
const notification=require('./notification.service');
const logService=require('./log.service');
const {applyUserStatusTransition}=require('./userStatusTransition.service');
function err(m,s){const e=new Error(m);e.statusCode=s;return e;}
function mapUserStatusTransitionError(error){ if(error.code==='USER_STATUS_TARGET_NOT_FOUND') return err('Usuario reportado no encontrado.',404); if(error.code==='USER_STATUS_CONFLICT') return err('El estado del usuario cambió. Intente nuevamente.',409); if(error.code==='USER_TOKEN_VERSION_UPDATE_FAILED') return err('Error al actualizar el estado del usuario.',500); return error; }
async function report(user,targetId,payload,ip){ const rid=Number(targetId); if(rid===Number(user.id)) throw err('No puede reportarse a sí mismo.',400); const target=await model.findUser(rid); if(!target) throw err('Usuario reportado no encontrado.',404); const dup=await model.duplicate(rid,user.id); if(dup) throw err('Ya existe un reporte pendiente o revisado hacia este usuario.',409); const conn=await pool.getConnection(); try{ await conn.beginTransaction(); const rep=await model.create({usuario_reportado_id:rid,usuario_reportante_id:user.id,motivo:payload.motivo,descripcion:payload.descripcion},conn); const [admins]=await conn.query(`SELECT u.id FROM usuarios u INNER JOIN roles r ON r.id=u.rol_id WHERE r.nombre='administrador' AND u.estado='activo'`); for(const a of admins){ await notification.create(conn,a.id,{tipo:'nuevo_reporte_usuario',titulo:'Nuevo reporte de usuario',mensaje:'Un usuario fue reportado.',entidad_tipo:'reportes_usuarios',entidad_id:rep.id,url_destino:'/pages/admin-reports-users.html'}); } await logService.log(conn,{usuario_id:user.id,accion:'usuario_reportado',entidad:'reportes_usuarios',entidad_id:rep.id,detalle:{usuario_reportado_id:rid},ip}); await conn.commit(); return rep; }catch(e){ await conn.rollback(); throw e; } finally{ conn.release(); } }
async function list(query){ const limit=Math.min(Math.max(parseInt(query.limit||'20',10),1),100); const page=Math.max(parseInt(query.page||'1',10),1); return {reports:await model.list({limit,offset:(page-1)*limit,estado:query.estado}),pagination:{page,limit}}; }
async function update(admin,id,payload,ip){ const conn=await pool.getConnection(); try{ await conn.beginTransaction(); const report=await model.findById(id,conn); if(!report) throw err('Reporte de usuario no encontrado.',404); const shouldInactivate=payload.estado==='accionado' && Boolean(payload.inactivar_usuario); if(shouldInactivate && Number(report.usuario_reportado_id)===Number(admin.id)) throw err('No puede inactivarse a sí mismo.',400); await model.update(id,payload,conn); if(shouldInactivate){ try{ await applyUserStatusTransition({conn,userId:report.usuario_reportado_id,requestedEstado:'inactivo'}); }catch(error){ throw mapUserStatusTransitionError(error); } await notification.create(conn,report.usuario_reportado_id,{tipo:'usuario_inactivado',titulo:'Cuenta inactivada',mensaje:'Tu cuenta fue inactivada por revisión administrativa.',entidad_tipo:'usuarios',entidad_id:report.usuario_reportado_id,url_destino:'/pages/account-settings.html'}); } if(report.usuario_reportante_id){ await notification.create(conn,report.usuario_reportante_id,{tipo:'reporte_respondido',titulo:'Reporte revisado',mensaje:'Tu reporte de usuario fue actualizado.',entidad_tipo:'reportes_usuarios',entidad_id:id,url_destino:'/pages/notifications.html'}); } await logService.log(conn,{usuario_id:admin.id,accion:'reporte_usuario_actualizado',entidad:'reportes_usuarios',entidad_id:id,detalle:{estado:payload.estado,inactivar_usuario:Boolean(payload.inactivar_usuario)},ip}); const finalReport=await model.findById(id,conn); await conn.commit(); return finalReport; }catch(e){ await conn.rollback(); throw e; } finally{ conn.release(); } }
module.exports={report,list,update};
