const express=require('express'); const c=require('../controllers/chat.controller'); const authRequired=require('../middlewares/authRequired'); const presenceTouch=require('../middlewares/presenceTouch'); const {createConversationValidator,messageValidator}=require('../validators/chat.validators'); const { chatUpload, multerErrorHandler } = require('../middlewares/upload.middleware');
const router=express.Router();
const chatAuth=[authRequired,presenceTouch];
router.get('/conversations',...chatAuth,c.list);
router.post('/conversations',...chatAuth,createConversationValidator,c.create);
router.get('/conversations/:id/messages',...chatAuth,c.messages);
router.post('/conversations/:id/messages',...chatAuth,chatUpload.array('files',5),multerErrorHandler,messageValidator,c.send);
router.patch('/conversations/:id/read',...chatAuth,c.read);
router.patch('/messages/:id/report',...chatAuth,c.report);
router.delete('/messages/:id',...chatAuth,c.remove);
module.exports=router;
